# This Docker Compose file can be used to restore a backup schema to a local host


version: "3.2"
services:
   dgraph-init:
    image: dgraph/dgraph:v21.03.1
    volumes:
      - ./dgraph/schema:/dgraph/schema
    command: >
      sh -c "curl -X POST host.docker.internal:8080/admin/schema --data-binary '@./schema/libreSchema.sdl' &&
             dgraph live -f ./schema/g01.rdf.gz -a host.docker.internal:9080 -z host.docker.internal:5080"
    container_name: dgraph-seed
